apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config/configmap.yaml
  - config/secret.yaml
  - base/postgres-statefulset.yaml
  - base/redis-statefulset.yaml
  - apps/api-deployment.yaml
  - apps/worker-deployment.yaml
  - apps/market-crawler-deployment.yaml
  - ingress.yaml
