import os
from openai import AsyncOpenAI
import logging

logger = logging.getLogger(__name__)

# Scaffold: If no API key, use mock response.
API_KEY = os.environ.get("OPENAI_API_KEY", "")
client = AsyncOpenAI(api_key=API_KEY) if API_KEY else None

async def generate_market_analysis(news_data: list, power_data: list, memory_data: list) -> str:
    """
    Feeds crawled macro data to an LLM to generate a professional daily briefing.
    """
    logger.info("Generating AI Market Analysis from LLM...")
    
    prompt = f"""
    You are a senior data center infrastructure analyst.
    Write a 3-paragraph executive summary based on the following data:
    News: {news_data}
    Power: {power_data}
    Memory: {memory_data}
    Focus on supply chain constraints and power costs.
    """

    if client:
        try:
            response = await client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                max_tokens=300
            )
            return response.choices[0].message.content
        except Exception as e:
            logger.error(f"LLM Generation failed: {str(e)}")
            return _get_mock_analysis()
    else:
        # Fallback for scaffold / local testing without API key
        return _get_mock_analysis()

def _get_mock_analysis() -> str:
    return (
        "AI Infrastructure Market Analysis (Auto-generated by AI):\n\n"
        "The global datacenter market is facing significant headwinds in Q3. "
        "With AWS announcing a massive $10B investment in Mississippi, hyperscalers continue to secure power and land. "
        "However, Korean authorities are restricting new high-density power permits in Seoul, forcing operators to look elsewhere.\n\n"
        "On the hardware front, HBM3E supply remains extremely constrained. Spot prices for estimated stacks are hovering around $4,500, "
        "with lead times extending beyond 40 weeks. DDR5 128GB R-DIMMs are stable at $320, but the bottleneck remains entirely in advanced packaging.\n\n"
        "Power grids are showing divergence. Texas (ERCOT) remains highly attractive at $0.08/kWh, while Virginia (PJM) and South Korea "
        "are seeing upward pressure due to grid congestion and regulatory changes. Liquid cooling is rapidly becoming a mandatory requirement for next-gen clusters."
    )
