"""Refactor user tables

Revision ID: 0c71f41d0ff2
Revises: f4d7a3f426bd
Create Date: 2026-07-23 15:00:13.697315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c71f41d0ff2'
down_revision: Union[str, Sequence[str], None] = 'f4d7a3f426bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawler_configs',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('target_urls', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawler_configs_name'), 'crawler_configs', ['name'], unique=True)
    op.create_table('user_bas',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bas_email'), 'user_bas', ['email'], unique=True)
    op.create_index(op.f('ix_user_bas_nickname'), 'user_bas', ['nickname'], unique=True)
    op.create_index(op.f('ix_user_bas_oauth_id'), 'user_bas', ['oauth_id'], unique=True)
    op.create_table('user_flw',
    sa.Column('follower_id', sa.Uuid(), nullable=False),
    sa.Column('following_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user_bas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['user_bas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    op.create_table('user_fvrt',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_bas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_fvrt_target_id'), 'user_fvrt', ['target_id'], unique=False)
    op.create_index(op.f('ix_user_fvrt_target_type'), 'user_fvrt', ['target_type'], unique=False)
    op.create_index(op.f('ix_user_fvrt_user_id'), 'user_fvrt', ['user_id'], unique=False)
    op.create_table('user_stng',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_bas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stng_user_id'), 'user_stng', ['user_id'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_constraint(op.f('login_history_user_id_fkey'), 'login_history', type_='foreignkey')
    op.drop_table('users')
    op.create_foreign_key(None, 'login_history', 'user_bas', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'login_history', type_='foreignkey')
    op.create_foreign_key(op.f('login_history_user_id_fkey'), 'login_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nickname', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('oauth_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('oauth_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('nickname', name=op.f('users_nickname_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_user_stng_user_id'), table_name='user_stng')
    op.drop_table('user_stng')
    op.drop_index(op.f('ix_user_fvrt_user_id'), table_name='user_fvrt')
    op.drop_index(op.f('ix_user_fvrt_target_type'), table_name='user_fvrt')
    op.drop_index(op.f('ix_user_fvrt_target_id'), table_name='user_fvrt')
    op.drop_table('user_fvrt')
    op.drop_table('user_flw')
    op.drop_index(op.f('ix_user_bas_oauth_id'), table_name='user_bas')
    op.drop_index(op.f('ix_user_bas_nickname'), table_name='user_bas')
    op.drop_index(op.f('ix_user_bas_email'), table_name='user_bas')
    op.drop_table('user_bas')
    op.drop_index(op.f('ix_crawler_configs_name'), table_name='crawler_configs')
    op.drop_table('crawler_configs')
    # ### end Alembic commands ###
