"""Add batch schedule tables

Revision ID: 156fdbca733f
Revises: ba50dd389d86
Create Date: 2026-07-23 13:50:59.210479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156fdbca733f'
down_revision: Union[str, Sequence[str], None] = 'ba50dd389d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SYS_BAT_SCH_BAS',
    sa.Column('BAT_ID', sa.String(length=50), nullable=False, comment='배치 마스터 ID'),
    sa.Column('BAT_NM', sa.String(length=100), nullable=False, comment='배치 그룹명'),
    sa.Column('RUN_HR', sa.String(length=50), nullable=True, comment='실행 시간(시)'),
    sa.Column('RUN_MIN', sa.String(length=50), nullable=True, comment='실행 시간(분)'),
    sa.Column('RUN_SEC', sa.String(length=50), nullable=True, comment='실행 시간(초)'),
    sa.Column('USE_YN', sa.String(length=1), nullable=True, comment='사용 여부'),
    sa.Column('REF_VAL_1', sa.String(length=200), nullable=True, comment='참조값 1'),
    sa.Column('REF_VAL_2', sa.String(length=200), nullable=True, comment='참조값 2'),
    sa.Column('REF_VAL_3', sa.String(length=200), nullable=True, comment='참조값 3'),
    sa.Column('LAST_RUN_DT', sa.DateTime(), nullable=True, comment='마지막 실행 일시'),
    sa.Column('NXT_RUN_DT', sa.DateTime(), nullable=True, comment='다음 실행 예정 일시'),
    sa.Column('ERR_MSG', sa.Text(), nullable=True, comment='에러 메시지'),
    sa.Column('CRT_DT', sa.DateTime(), nullable=True, comment='생성일시'),
    sa.Column('UPD_DT', sa.DateTime(), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('BAT_ID')
    )
    op.create_index(op.f('ix_SYS_BAT_SCH_BAS_BAT_ID'), 'SYS_BAT_SCH_BAS', ['BAT_ID'], unique=False)
    op.create_table('SYS_BAT_SCH_DTL',
    sa.Column('BAT_ID', sa.String(length=50), nullable=False, comment='배치 마스터 ID'),
    sa.Column('JOB_ID', sa.String(length=50), nullable=False, comment='세부 잡 ID'),
    sa.Column('JOB_NM', sa.String(length=100), nullable=False, comment='세부 잡명'),
    sa.Column('EXEC_TYP', sa.String(length=20), nullable=False, comment='실행 방식 (SCRIPT, API, PLAYWRIGHT 등)'),
    sa.Column('EXEC_PATH', sa.String(length=255), nullable=False, comment='실행 경로/URL'),
    sa.Column('RUN_ORD', sa.Integer(), nullable=True, comment='실행 순서'),
    sa.Column('USE_YN', sa.String(length=1), nullable=True, comment='사용 여부'),
    sa.Column('REF_VAL_1', sa.String(length=200), nullable=True, comment='파라미터/참조값 1'),
    sa.Column('REF_VAL_2', sa.String(length=200), nullable=True, comment='파라미터/참조값 2'),
    sa.Column('REF_VAL_3', sa.String(length=200), nullable=True, comment='파라미터/참조값 3'),
    sa.Column('LAST_RUN_DT', sa.DateTime(), nullable=True, comment='마지막 실행 일시'),
    sa.Column('ERR_MSG', sa.Text(), nullable=True, comment='에러 메시지'),
    sa.Column('CRT_DT', sa.DateTime(), nullable=True, comment='생성일시'),
    sa.Column('UPD_DT', sa.DateTime(), nullable=True, comment='수정일시'),
    sa.ForeignKeyConstraint(['BAT_ID'], ['SYS_BAT_SCH_BAS.BAT_ID'], ),
    sa.PrimaryKeyConstraint('BAT_ID', 'JOB_ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SYS_BAT_SCH_DTL')
    op.drop_index(op.f('ix_SYS_BAT_SCH_BAS_BAT_ID'), table_name='SYS_BAT_SCH_BAS')
    op.drop_table('SYS_BAT_SCH_BAS')
    # ### end Alembic commands ###
