"""phase2_market_schema

Revision ID: 1b9a0da43d80
Revises: 3fc4d2beec37
Create Date: 2026-07-23 16:40:29.077397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9a0da43d80'
down_revision: Union[str, Sequence[str], None] = '3fc4d2beec37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_market_product',
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('product_line', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('generation', sa.String(length=50), nullable=True),
    sa.Column('vram_gb', sa.Float(), nullable=True),
    sa.Column('memory_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_market_product_category'), 'tbl_market_product', ['category'], unique=False)
    op.create_index(op.f('ix_tbl_market_product_manufacturer'), 'tbl_market_product', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_tbl_market_product_model_name'), 'tbl_market_product', ['model_name'], unique=False)
    op.create_table('tbl_market_rental',
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('instance_name', sa.String(length=200), nullable=False),
    sa.Column('hardware_model', sa.String(length=200), nullable=False),
    sa.Column('hourly_price', sa.Float(), nullable=False),
    sa.Column('monthly_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('is_contract', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_rental_hw_time', 'tbl_market_rental', ['hardware_model', 'observed_at'], unique=False)
    op.create_index(op.f('ix_tbl_market_rental_hardware_model'), 'tbl_market_rental', ['hardware_model'], unique=False)
    op.create_index(op.f('ix_tbl_market_rental_instance_name'), 'tbl_market_rental', ['instance_name'], unique=False)
    op.create_index(op.f('ix_tbl_market_rental_observed_at'), 'tbl_market_rental', ['observed_at'], unique=False)
    op.create_index(op.f('ix_tbl_market_rental_provider'), 'tbl_market_rental', ['provider'], unique=False)
    op.create_table('tbl_market_listing',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['tbl_market_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_market_listing_product_id'), 'tbl_market_listing', ['product_id'], unique=False)
    op.create_index(op.f('ix_tbl_market_listing_url'), 'tbl_market_listing', ['url'], unique=True)
    op.create_index(op.f('ix_tbl_market_listing_vendor_name'), 'tbl_market_listing', ['vendor_name'], unique=False)
    op.create_table('tbl_market_price_obs',
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('shipping_fee', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['tbl_market_listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_obs_listing_time', 'tbl_market_price_obs', ['listing_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_tbl_market_price_obs_listing_id'), 'tbl_market_price_obs', ['listing_id'], unique=False)
    op.create_index(op.f('ix_tbl_market_price_obs_observed_at'), 'tbl_market_price_obs', ['observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_market_price_obs_observed_at'), table_name='tbl_market_price_obs')
    op.drop_index(op.f('ix_tbl_market_price_obs_listing_id'), table_name='tbl_market_price_obs')
    op.drop_index('idx_market_obs_listing_time', table_name='tbl_market_price_obs')
    op.drop_table('tbl_market_price_obs')
    op.drop_index(op.f('ix_tbl_market_listing_vendor_name'), table_name='tbl_market_listing')
    op.drop_index(op.f('ix_tbl_market_listing_url'), table_name='tbl_market_listing')
    op.drop_index(op.f('ix_tbl_market_listing_product_id'), table_name='tbl_market_listing')
    op.drop_table('tbl_market_listing')
    op.drop_index(op.f('ix_tbl_market_rental_provider'), table_name='tbl_market_rental')
    op.drop_index(op.f('ix_tbl_market_rental_observed_at'), table_name='tbl_market_rental')
    op.drop_index(op.f('ix_tbl_market_rental_instance_name'), table_name='tbl_market_rental')
    op.drop_index(op.f('ix_tbl_market_rental_hardware_model'), table_name='tbl_market_rental')
    op.drop_index('idx_market_rental_hw_time', table_name='tbl_market_rental')
    op.drop_table('tbl_market_rental')
    op.drop_index(op.f('ix_tbl_market_product_model_name'), table_name='tbl_market_product')
    op.drop_index(op.f('ix_tbl_market_product_manufacturer'), table_name='tbl_market_product')
    op.drop_index(op.f('ix_tbl_market_product_category'), table_name='tbl_market_product')
    op.drop_table('tbl_market_product')
    # ### end Alembic commands ###
