"""Initial schema

Revision ID: 300276d985a7
Revises: 
Create Date: 2026-07-22 09:01:56.552768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300276d985a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_licenses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('collection_allowed', sa.Boolean(), nullable=False),
    sa.Column('public_display_allowed', sa.Boolean(), nullable=False),
    sa.Column('redistribution_allowed', sa.Boolean(), nullable=False),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gpu_manufacturers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('providers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('official_homepage', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=True)
    op.create_index(op.f('ix_providers_slug'), 'providers', ['slug'], unique=True)
    op.create_table('collection_runs',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('items_collected', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_runs_provider_id'), 'collection_runs', ['provider_id'], unique=False)
    op.create_table('gpu_models',
    sa.Column('manufacturer_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['gpu_manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_gpu_models_manufacturer_id'), 'gpu_models', ['manufacturer_id'], unique=False)
    op.create_table('provider_regions',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('provider_region_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_regions_provider_id'), 'provider_regions', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_regions_provider_region_id'), 'provider_regions', ['provider_region_id'], unique=False)
    op.create_table('source_attributions',
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('license_id', sa.Uuid(), nullable=False),
    sa.Column('attribution_text', sa.Text(), nullable=False),
    sa.Column('official_source_url', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['data_licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_attributions_provider_id'), 'source_attributions', ['provider_id'], unique=False)
    op.create_table('gpu_variants',
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('form_factor', sa.String(length=50), nullable=True),
    sa.Column('vram_gb', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['gpu_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpu_variants_model_id'), 'gpu_variants', ['model_id'], unique=False)
    op.create_table('instance_offerings',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('machine_type_name', sa.String(length=255), nullable=False),
    sa.Column('includes_cpu', sa.Boolean(), nullable=False),
    sa.Column('includes_ram', sa.Boolean(), nullable=False),
    sa.Column('includes_local_storage', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['provider_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instance_offerings_machine_type_name'), 'instance_offerings', ['machine_type_name'], unique=False)
    op.create_index(op.f('ix_instance_offerings_provider_id'), 'instance_offerings', ['provider_id'], unique=False)
    op.create_index(op.f('ix_instance_offerings_region_id'), 'instance_offerings', ['region_id'], unique=False)
    op.create_table('price_alerts',
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('gpu_model_id', sa.Uuid(), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gpu_model_id'], ['gpu_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_gpu_model_id'), 'price_alerts', ['gpu_model_id'], unique=False)
    op.create_index(op.f('ix_price_alerts_user_email'), 'price_alerts', ['user_email'], unique=False)
    op.create_table('offering_gpu_configurations',
    sa.Column('offering_id', sa.Uuid(), nullable=False),
    sa.Column('gpu_variant_id', sa.Uuid(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gpu_variant_id'], ['gpu_variants.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['instance_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offering_gpu_configurations_gpu_variant_id'), 'offering_gpu_configurations', ['gpu_variant_id'], unique=False)
    op.create_index(op.f('ix_offering_gpu_configurations_offering_id'), 'offering_gpu_configurations', ['offering_id'], unique=False)
    op.create_table('pricing_plans',
    sa.Column('offering_id', sa.Uuid(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('billing_increment_seconds', sa.Integer(), nullable=False),
    sa.Column('minimum_billing_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['instance_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_plans_offering_id'), 'pricing_plans', ['offering_id'], unique=False)
    op.create_table('price_observations',
    sa.Column('pricing_plan_id', sa.Uuid(), nullable=False),
    sa.Column('source_price', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('source_currency', sa.String(length=3), nullable=False),
    sa.Column('source_unit', sa.String(length=50), nullable=False),
    sa.Column('normalized_hourly_price', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('normalized_gpu_hour_price', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('normalized_vram_gb_hour_price', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('normalized_monthly_price', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('availability_status', sa.String(length=50), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pricing_plan_id'], ['pricing_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_observations_pricing_plan_id'), 'price_observations', ['pricing_plan_id'], unique=False)
    op.create_table('data_quality_issues',
    sa.Column('observation_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['price_observations.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['collection_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_issues_observation_id'), 'data_quality_issues', ['observation_id'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_run_id'), 'data_quality_issues', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_quality_issues_run_id'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_observation_id'), table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    op.drop_index(op.f('ix_price_observations_pricing_plan_id'), table_name='price_observations')
    op.drop_table('price_observations')
    op.drop_index(op.f('ix_pricing_plans_offering_id'), table_name='pricing_plans')
    op.drop_table('pricing_plans')
    op.drop_index(op.f('ix_offering_gpu_configurations_offering_id'), table_name='offering_gpu_configurations')
    op.drop_index(op.f('ix_offering_gpu_configurations_gpu_variant_id'), table_name='offering_gpu_configurations')
    op.drop_table('offering_gpu_configurations')
    op.drop_index(op.f('ix_price_alerts_user_email'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_gpu_model_id'), table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_index(op.f('ix_instance_offerings_region_id'), table_name='instance_offerings')
    op.drop_index(op.f('ix_instance_offerings_provider_id'), table_name='instance_offerings')
    op.drop_index(op.f('ix_instance_offerings_machine_type_name'), table_name='instance_offerings')
    op.drop_table('instance_offerings')
    op.drop_index(op.f('ix_gpu_variants_model_id'), table_name='gpu_variants')
    op.drop_table('gpu_variants')
    op.drop_index(op.f('ix_source_attributions_provider_id'), table_name='source_attributions')
    op.drop_table('source_attributions')
    op.drop_index(op.f('ix_provider_regions_provider_region_id'), table_name='provider_regions')
    op.drop_index(op.f('ix_provider_regions_provider_id'), table_name='provider_regions')
    op.drop_table('provider_regions')
    op.drop_index(op.f('ix_gpu_models_manufacturer_id'), table_name='gpu_models')
    op.drop_table('gpu_models')
    op.drop_index(op.f('ix_collection_runs_provider_id'), table_name='collection_runs')
    op.drop_table('collection_runs')
    op.drop_index(op.f('ix_providers_slug'), table_name='providers')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_table('providers')
    op.drop_table('gpu_manufacturers')
    op.drop_table('data_licenses')
    # ### end Alembic commands ###
