"""phase1_news_schema

Revision ID: 3fc4d2beec37
Revises: b705f9282bbb
Create Date: 2026-07-23 16:35:46.064273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fc4d2beec37'
down_revision: Union[str, Sequence[str], None] = 'b705f9282bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_news_arti', sa.Column('title', sa.String(length=500), nullable=False))
    op.add_column('tbl_news_arti', sa.Column('url', sa.String(length=1000), nullable=False))
    op.add_column('tbl_news_arti', sa.Column('canonical_url', sa.String(length=1000), nullable=True))
    op.add_column('tbl_news_arti', sa.Column('source_name', sa.String(length=100), nullable=False))
    op.add_column('tbl_news_arti', sa.Column('source_domain', sa.String(length=100), nullable=True))
    op.add_column('tbl_news_arti', sa.Column('author', sa.String(length=100), nullable=True))
    op.add_column('tbl_news_arti', sa.Column('published_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tbl_news_arti', sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tbl_news_arti', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('tbl_news_arti', sa.Column('thumbnail_url', sa.String(length=1000), nullable=True))
    op.add_column('tbl_news_arti', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('tbl_news_arti', sa.Column('content_type', sa.String(length=50), nullable=False))
    op.add_column('tbl_news_arti', sa.Column('is_semiconductor_related', sa.Boolean(), nullable=False))
    op.add_column('tbl_news_arti', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('tbl_news_arti', sa.Column('categories', sa.JSON(), nullable=True))
    op.add_column('tbl_news_arti', sa.Column('matched_keywords', sa.String(length=500), nullable=True))
    op.add_column('tbl_news_arti', sa.Column('collection_tier', sa.String(length=50), nullable=True))
    op.add_column('tbl_news_arti', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.add_column('tbl_news_arti', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tbl_news_arti', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_tbl_news_arti_arti_url'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_crt_ts'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_pub_ts'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_src_nm'), table_name='tbl_news_arti')
    op.drop_index(op.f('idx_news_arti_pub_src'), table_name='tbl_news_arti')
    op.create_index('idx_news_arti_pub_src', 'tbl_news_arti', ['published_at', 'source_name'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_category'), 'tbl_news_arti', ['category'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_content_type'), 'tbl_news_arti', ['content_type'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_created_at'), 'tbl_news_arti', ['created_at'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_published_at'), 'tbl_news_arti', ['published_at'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_source_name'), 'tbl_news_arti', ['source_name'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_url'), 'tbl_news_arti', ['url'], unique=True)
    op.drop_column('tbl_news_arti', 'crt_ts')
    op.drop_column('tbl_news_arti', 'clct_tr')
    op.drop_column('tbl_news_arti', 'src_nm')
    op.drop_column('tbl_news_arti', 'sum_txt')
    op.drop_column('tbl_news_arti', 'pub_ts')
    op.drop_column('tbl_news_arti', 'arti_url')
    op.drop_column('tbl_news_arti', 'kwd_txt')
    op.drop_column('tbl_news_arti', 'titl_nm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_news_arti', sa.Column('titl_nm', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('tbl_news_arti', sa.Column('kwd_txt', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('tbl_news_arti', sa.Column('arti_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.add_column('tbl_news_arti', sa.Column('pub_ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('tbl_news_arti', sa.Column('sum_txt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tbl_news_arti', sa.Column('src_nm', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('tbl_news_arti', sa.Column('clct_tr', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tbl_news_arti', sa.Column('crt_ts', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tbl_news_arti_url'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_source_name'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_published_at'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_created_at'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_content_type'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_category'), table_name='tbl_news_arti')
    op.drop_index('idx_news_arti_pub_src', table_name='tbl_news_arti')
    op.create_index(op.f('idx_news_arti_pub_src'), 'tbl_news_arti', ['pub_ts', 'src_nm'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_src_nm'), 'tbl_news_arti', ['src_nm'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_pub_ts'), 'tbl_news_arti', ['pub_ts'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_crt_ts'), 'tbl_news_arti', ['crt_ts'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_arti_url'), 'tbl_news_arti', ['arti_url'], unique=True)
    op.drop_column('tbl_news_arti', 'updated_at')
    op.drop_column('tbl_news_arti', 'created_at')
    op.drop_column('tbl_news_arti', 'metadata_json')
    op.drop_column('tbl_news_arti', 'collection_tier')
    op.drop_column('tbl_news_arti', 'matched_keywords')
    op.drop_column('tbl_news_arti', 'categories')
    op.drop_column('tbl_news_arti', 'category')
    op.drop_column('tbl_news_arti', 'is_semiconductor_related')
    op.drop_column('tbl_news_arti', 'content_type')
    op.drop_column('tbl_news_arti', 'language')
    op.drop_column('tbl_news_arti', 'thumbnail_url')
    op.drop_column('tbl_news_arti', 'summary')
    op.drop_column('tbl_news_arti', 'collected_at')
    op.drop_column('tbl_news_arti', 'published_at')
    op.drop_column('tbl_news_arti', 'author')
    op.drop_column('tbl_news_arti', 'source_domain')
    op.drop_column('tbl_news_arti', 'source_name')
    op.drop_column('tbl_news_arti', 'canonical_url')
    op.drop_column('tbl_news_arti', 'url')
    op.drop_column('tbl_news_arti', 'title')
    # ### end Alembic commands ###
