"""Add tbl_daily_report

Revision ID: 576a294b22a9
Revises: 87f886fd8c93
Create Date: 2026-07-24 01:02:17.082554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576a294b22a9'
down_revision: Union[str, Sequence[str], None] = '87f886fd8c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_daily_report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date', 'report_type', name='uq_daily_report_date_type')
    )
    op.create_index(op.f('ix_tbl_daily_report_report_date'), 'tbl_daily_report', ['report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_daily_report_report_date'), table_name='tbl_daily_report')
    op.drop_table('tbl_daily_report')
    # ### end Alembic commands ###
