"""Add StoragePriceHistory model

Revision ID: 6c173bf6eec7
Revises: 1b9a0da43d80
Create Date: 2026-07-23 18:09:15.787771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c173bf6eec7'
down_revision: Union[str, Sequence[str], None] = '1b9a0da43d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_storage_prc_hist',
    sa.Column('prv_id', sa.String(length=50), nullable=False),
    sa.Column('storage_mdl', sa.String(length=100), nullable=False),
    sa.Column('prc_pgb_mth', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_storage_prc_hist_prv_id'), 'tbl_storage_prc_hist', ['prv_id'], unique=False)
    op.create_index(op.f('ix_tbl_storage_prc_hist_storage_mdl'), 'tbl_storage_prc_hist', ['storage_mdl'], unique=False)
    op.create_index(op.f('ix_tbl_storage_prc_hist_ts'), 'tbl_storage_prc_hist', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_storage_prc_hist_ts'), table_name='tbl_storage_prc_hist')
    op.drop_index(op.f('ix_tbl_storage_prc_hist_storage_mdl'), table_name='tbl_storage_prc_hist')
    op.drop_index(op.f('ix_tbl_storage_prc_hist_prv_id'), table_name='tbl_storage_prc_hist')
    op.drop_table('tbl_storage_prc_hist')
    # ### end Alembic commands ###
