"""add_market_ohlc_daily_table

Revision ID: 7402e5853cfc
Revises: 6c173bf6eec7
Create Date: 2026-07-23 22:42:27.112785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7402e5853cfc'
down_revision: Union[str, Sequence[str], None] = '6c173bf6eec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_market_ohlc_daily',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('vendor_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['tbl_market_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'trade_date', name='uq_ohlc_product_date')
    )
    op.create_index('idx_ohlc_product_date', 'tbl_market_ohlc_daily', ['product_id', 'trade_date'], unique=False)
    op.create_index(op.f('ix_tbl_market_ohlc_daily_product_id'), 'tbl_market_ohlc_daily', ['product_id'], unique=False)
    op.create_index(op.f('ix_tbl_market_ohlc_daily_trade_date'), 'tbl_market_ohlc_daily', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_market_ohlc_daily_trade_date'), table_name='tbl_market_ohlc_daily')
    op.drop_index(op.f('ix_tbl_market_ohlc_daily_product_id'), table_name='tbl_market_ohlc_daily')
    op.drop_index('idx_ohlc_product_date', table_name='tbl_market_ohlc_daily')
    op.drop_table('tbl_market_ohlc_daily')
    # ### end Alembic commands ###
