"""Initial schema

Revision ID: a00ecbf6abd3
Revises: 
Create Date: 2026-07-23 12:03:10.871022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00ecbf6abd3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SYS_CD_BAS',
    sa.Column('SYS_GROUP_ID', sa.String(length=50), nullable=False),
    sa.Column('SYS_CD_ID', sa.String(length=50), nullable=False),
    sa.Column('SYS_CD_NM', sa.String(length=100), nullable=False),
    sa.Column('CRT_DT', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UPD_DT', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('DESC_TXT', sa.Text(), nullable=True),
    sa.Column('REF_VAL_1', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_2', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_3', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_4', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_5', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_6', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_7', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_8', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_9', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_10', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('SYS_GROUP_ID', 'SYS_CD_ID')
    )
    op.create_table('SYS_CD_GROUP_BAS',
    sa.Column('SYS_GROUP_ID', sa.String(length=50), nullable=False),
    sa.Column('GRP_NM', sa.String(length=100), nullable=False),
    sa.Column('CRT_DT', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UPD_DT', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('DESC_TXT', sa.Text(), nullable=True),
    sa.Column('REF_VAL_1', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_2', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_3', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_4', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_5', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_6', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_7', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_8', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_9', sa.String(length=200), nullable=True),
    sa.Column('REF_VAL_10', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('SYS_GROUP_ID')
    )
    op.create_table('collection_runs',
    sa.Column('provider_id', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('items_collected', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_runs_provider_id'), 'collection_runs', ['provider_id'], unique=False)
    op.create_index('ix_collection_runs_provider_started', 'collection_runs', ['provider_id', 'started_at'], unique=False)
    op.create_table('cpu_manufacturers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('data_licenses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('collection_allowed', sa.Boolean(), nullable=False),
    sa.Column('public_display_allowed', sa.Boolean(), nullable=False),
    sa.Column('redistribution_allowed', sa.Boolean(), nullable=False),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_quality_issues',
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('observation_id', sa.String(length=36), nullable=True),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('raw_data_snapshot', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_issues_observation_id'), 'data_quality_issues', ['observation_id'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_run_id'), 'data_quality_issues', ['run_id'], unique=False)
    op.create_table('gpu_manufacturers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=True)
    op.create_table('memory_manufacturers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_manufacturers_name'), 'memory_manufacturers', ['name'], unique=True)
    op.create_table('providers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('official_homepage', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=True)
    op.create_index(op.f('ix_providers_slug'), 'providers', ['slug'], unique=True)
    op.create_table('schedule_configs',
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('cron_expression', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_configs_provider_id'), 'schedule_configs', ['provider_id'], unique=False)
    op.create_table('storage_providers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_providers_name'), 'storage_providers', ['name'], unique=True)
    op.create_table('tbl_fin_mkt_hist',
    sa.Column('ast_typ', sa.String(length=50), nullable=False),
    sa.Column('sym_cd', sa.String(length=100), nullable=False),
    sa.Column('opn_prc', sa.Float(), nullable=False),
    sa.Column('hi_prc', sa.Float(), nullable=False),
    sa.Column('lo_prc', sa.Float(), nullable=False),
    sa.Column('cls_prc', sa.Float(), nullable=False),
    sa.Column('vol_cnt', sa.Float(), nullable=True),
    sa.Column('crncy_cd', sa.String(length=10), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fin_mkt_sym_ts', 'tbl_fin_mkt_hist', ['sym_cd', 'ts'], unique=False)
    op.create_index(op.f('ix_tbl_fin_mkt_hist_ast_typ'), 'tbl_fin_mkt_hist', ['ast_typ'], unique=False)
    op.create_index(op.f('ix_tbl_fin_mkt_hist_sym_cd'), 'tbl_fin_mkt_hist', ['sym_cd'], unique=False)
    op.create_index(op.f('ix_tbl_fin_mkt_hist_ts'), 'tbl_fin_mkt_hist', ['ts'], unique=False)
    op.create_table('tbl_gpu_prc_hist',
    sa.Column('prv_id', sa.String(length=50), nullable=False),
    sa.Column('hw_typ', sa.String(length=20), nullable=False),
    sa.Column('gpu_mdl', sa.String(length=100), nullable=True),
    sa.Column('vram_gb', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cpu_mdl', sa.String(length=100), nullable=True),
    sa.Column('core_cnt', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('prc_ph', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('avl_st', sa.String(length=50), nullable=False),
    sa.Column('prv_url', sa.String(length=500), nullable=True),
    sa.Column('sys_ram', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('tdp_w', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gpu_prc_mdl_ts', 'tbl_gpu_prc_hist', ['gpu_mdl', 'ts'], unique=False)
    op.create_index('idx_gpu_prc_prv_ts', 'tbl_gpu_prc_hist', ['prv_id', 'ts'], unique=False)
    op.create_index(op.f('ix_tbl_gpu_prc_hist_cpu_mdl'), 'tbl_gpu_prc_hist', ['cpu_mdl'], unique=False)
    op.create_index(op.f('ix_tbl_gpu_prc_hist_gpu_mdl'), 'tbl_gpu_prc_hist', ['gpu_mdl'], unique=False)
    op.create_index(op.f('ix_tbl_gpu_prc_hist_prv_id'), 'tbl_gpu_prc_hist', ['prv_id'], unique=False)
    op.create_index(op.f('ix_tbl_gpu_prc_hist_ts'), 'tbl_gpu_prc_hist', ['ts'], unique=False)
    op.create_table('tbl_news_arti',
    sa.Column('titl_nm', sa.String(length=500), nullable=False),
    sa.Column('arti_url', sa.String(length=1000), nullable=False),
    sa.Column('src_nm', sa.String(length=100), nullable=False),
    sa.Column('pub_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sum_txt', sa.Text(), nullable=True),
    sa.Column('kwd_txt', sa.String(length=500), nullable=True),
    sa.Column('clct_tr', sa.String(length=50), nullable=True),
    sa.Column('crt_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_arti_pub_src', 'tbl_news_arti', ['pub_ts', 'src_nm'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_arti_url'), 'tbl_news_arti', ['arti_url'], unique=True)
    op.create_index(op.f('ix_tbl_news_arti_crt_ts'), 'tbl_news_arti', ['crt_ts'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_pub_ts'), 'tbl_news_arti', ['pub_ts'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_src_nm'), 'tbl_news_arti', ['src_nm'], unique=False)
    op.create_table('tbl_obx_evt',
    sa.Column('tpc_nm', sa.String(length=255), nullable=False),
    sa.Column('evt_typ', sa.String(length=255), nullable=False),
    sa.Column('payld_dat', sa.JSON(), nullable=False),
    sa.Column('crt_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('proc_st', sa.Boolean(), nullable=False),
    sa.Column('proc_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_obx_evt_proc_st'), 'tbl_obx_evt', ['proc_st'], unique=False)
    op.create_index(op.f('ix_tbl_obx_evt_tpc_nm'), 'tbl_obx_evt', ['tpc_nm'], unique=False)
    op.create_table('tbl_rtl_prc_hist',
    sa.Column('pltf_nm', sa.String(length=50), nullable=False),
    sa.Column('hw_typ', sa.String(length=20), nullable=False),
    sa.Column('mfg_nm', sa.String(length=50), nullable=True),
    sa.Column('mdl_nm', sa.String(length=200), nullable=False),
    sa.Column('capa_gb', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('prc_amt', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('crncy_cd', sa.String(length=10), nullable=False),
    sa.Column('prd_url', sa.String(length=1000), nullable=True),
    sa.Column('is_offc', sa.Boolean(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rtl_prc_hw_mdl_ts', 'tbl_rtl_prc_hist', ['hw_typ', 'mdl_nm', 'ts'], unique=False)
    op.create_index('idx_rtl_prc_pltf_mdl_ts', 'tbl_rtl_prc_hist', ['pltf_nm', 'mdl_nm', 'ts'], unique=False)
    op.create_index(op.f('ix_tbl_rtl_prc_hist_mdl_nm'), 'tbl_rtl_prc_hist', ['mdl_nm'], unique=False)
    op.create_index(op.f('ix_tbl_rtl_prc_hist_pltf_nm'), 'tbl_rtl_prc_hist', ['pltf_nm'], unique=False)
    op.create_index(op.f('ix_tbl_rtl_prc_hist_ts'), 'tbl_rtl_prc_hist', ['ts'], unique=False)
    op.create_table('cpu_models',
    sa.Column('manufacturer_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['cpu_manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cpu_models_manufacturer_id'), 'cpu_models', ['manufacturer_id'], unique=False)
    op.create_table('gpu_models',
    sa.Column('manufacturer_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['gpu_manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_gpu_models_manufacturer_id'), 'gpu_models', ['manufacturer_id'], unique=False)
    op.create_table('memory_modules',
    sa.Column('manufacturer_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('capacity_gb', sa.Float(), nullable=False),
    sa.Column('speed_mhz', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['memory_manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_modules_manufacturer_id'), 'memory_modules', ['manufacturer_id'], unique=False)
    op.create_table('provider_regions',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('provider_region_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_regions_provider_id'), 'provider_regions', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_regions_provider_region_id'), 'provider_regions', ['provider_region_id'], unique=False)
    op.create_table('source_attributions',
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('license_id', sa.Uuid(), nullable=False),
    sa.Column('attribution_text', sa.Text(), nullable=False),
    sa.Column('official_source_url', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['data_licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_attributions_provider_id'), 'source_attributions', ['provider_id'], unique=False)
    op.create_table('storage_tiers',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price_per_gb_month', sa.Float(), nullable=False),
    sa.Column('egress_price_per_gb', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['storage_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_tiers_provider_id'), 'storage_tiers', ['provider_id'], unique=False)
    op.create_table('cpu_variants',
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cores', sa.Integer(), nullable=False),
    sa.Column('threads', sa.Integer(), nullable=False),
    sa.Column('base_clock_ghz', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['cpu_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpu_variants_model_id'), 'cpu_variants', ['model_id'], unique=False)
    op.create_table('gpu_variants',
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('form_factor', sa.String(length=50), nullable=True),
    sa.Column('vram_gb', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['gpu_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpu_variants_model_id'), 'gpu_variants', ['model_id'], unique=False)
    op.create_table('instance_offerings',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('machine_type_name', sa.String(length=255), nullable=False),
    sa.Column('includes_cpu', sa.Boolean(), nullable=False),
    sa.Column('includes_ram', sa.Boolean(), nullable=False),
    sa.Column('includes_local_storage', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['provider_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instance_offerings_machine_type_name'), 'instance_offerings', ['machine_type_name'], unique=False)
    op.create_index(op.f('ix_instance_offerings_provider_id'), 'instance_offerings', ['provider_id'], unique=False)
    op.create_index(op.f('ix_instance_offerings_region_id'), 'instance_offerings', ['region_id'], unique=False)
    op.create_table('price_alerts',
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('gpu_model_id', sa.Uuid(), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gpu_model_id'], ['gpu_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_gpu_model_id'), 'price_alerts', ['gpu_model_id'], unique=False)
    op.create_index(op.f('ix_price_alerts_user_email'), 'price_alerts', ['user_email'], unique=False)
    op.create_table('offering_cpu_configurations',
    sa.Column('offering_id', sa.Uuid(), nullable=False),
    sa.Column('cpu_variant_id', sa.Uuid(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cpu_variant_id'], ['cpu_variants.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['instance_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offering_cpu_configurations_cpu_variant_id'), 'offering_cpu_configurations', ['cpu_variant_id'], unique=False)
    op.create_index(op.f('ix_offering_cpu_configurations_offering_id'), 'offering_cpu_configurations', ['offering_id'], unique=False)
    op.create_table('offering_gpu_configurations',
    sa.Column('offering_id', sa.Uuid(), nullable=False),
    sa.Column('gpu_variant_id', sa.Uuid(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gpu_variant_id'], ['gpu_variants.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['instance_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offering_gpu_configurations_gpu_variant_id'), 'offering_gpu_configurations', ['gpu_variant_id'], unique=False)
    op.create_index(op.f('ix_offering_gpu_configurations_offering_id'), 'offering_gpu_configurations', ['offering_id'], unique=False)
    op.create_table('pricing_plans',
    sa.Column('offering_id', sa.Uuid(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('billing_increment_seconds', sa.Integer(), nullable=False),
    sa.Column('minimum_billing_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['instance_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_plans_offering_id'), 'pricing_plans', ['offering_id'], unique=False)
    op.create_table('price_observations',
    sa.Column('pricing_plan_id', sa.Uuid(), nullable=False),
    sa.Column('source_price', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('source_currency', sa.String(length=3), nullable=False),
    sa.Column('source_unit', sa.String(length=50), nullable=False),
    sa.Column('normalized_hourly_price', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('normalized_gpu_hour_price', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('normalized_vram_gb_hour_price', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('normalized_monthly_price', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('availability_status', sa.String(length=50), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pricing_plan_id'], ['pricing_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_observations_pricing_plan_id'), 'price_observations', ['pricing_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_observations_pricing_plan_id'), table_name='price_observations')
    op.drop_table('price_observations')
    op.drop_index(op.f('ix_pricing_plans_offering_id'), table_name='pricing_plans')
    op.drop_table('pricing_plans')
    op.drop_index(op.f('ix_offering_gpu_configurations_offering_id'), table_name='offering_gpu_configurations')
    op.drop_index(op.f('ix_offering_gpu_configurations_gpu_variant_id'), table_name='offering_gpu_configurations')
    op.drop_table('offering_gpu_configurations')
    op.drop_index(op.f('ix_offering_cpu_configurations_offering_id'), table_name='offering_cpu_configurations')
    op.drop_index(op.f('ix_offering_cpu_configurations_cpu_variant_id'), table_name='offering_cpu_configurations')
    op.drop_table('offering_cpu_configurations')
    op.drop_index(op.f('ix_price_alerts_user_email'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_gpu_model_id'), table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_index(op.f('ix_instance_offerings_region_id'), table_name='instance_offerings')
    op.drop_index(op.f('ix_instance_offerings_provider_id'), table_name='instance_offerings')
    op.drop_index(op.f('ix_instance_offerings_machine_type_name'), table_name='instance_offerings')
    op.drop_table('instance_offerings')
    op.drop_index(op.f('ix_gpu_variants_model_id'), table_name='gpu_variants')
    op.drop_table('gpu_variants')
    op.drop_index(op.f('ix_cpu_variants_model_id'), table_name='cpu_variants')
    op.drop_table('cpu_variants')
    op.drop_index(op.f('ix_storage_tiers_provider_id'), table_name='storage_tiers')
    op.drop_table('storage_tiers')
    op.drop_index(op.f('ix_source_attributions_provider_id'), table_name='source_attributions')
    op.drop_table('source_attributions')
    op.drop_index(op.f('ix_provider_regions_provider_region_id'), table_name='provider_regions')
    op.drop_index(op.f('ix_provider_regions_provider_id'), table_name='provider_regions')
    op.drop_table('provider_regions')
    op.drop_index(op.f('ix_memory_modules_manufacturer_id'), table_name='memory_modules')
    op.drop_table('memory_modules')
    op.drop_index(op.f('ix_gpu_models_manufacturer_id'), table_name='gpu_models')
    op.drop_table('gpu_models')
    op.drop_index(op.f('ix_cpu_models_manufacturer_id'), table_name='cpu_models')
    op.drop_table('cpu_models')
    op.drop_index(op.f('ix_tbl_rtl_prc_hist_ts'), table_name='tbl_rtl_prc_hist')
    op.drop_index(op.f('ix_tbl_rtl_prc_hist_pltf_nm'), table_name='tbl_rtl_prc_hist')
    op.drop_index(op.f('ix_tbl_rtl_prc_hist_mdl_nm'), table_name='tbl_rtl_prc_hist')
    op.drop_index('idx_rtl_prc_pltf_mdl_ts', table_name='tbl_rtl_prc_hist')
    op.drop_index('idx_rtl_prc_hw_mdl_ts', table_name='tbl_rtl_prc_hist')
    op.drop_table('tbl_rtl_prc_hist')
    op.drop_index(op.f('ix_tbl_obx_evt_tpc_nm'), table_name='tbl_obx_evt')
    op.drop_index(op.f('ix_tbl_obx_evt_proc_st'), table_name='tbl_obx_evt')
    op.drop_table('tbl_obx_evt')
    op.drop_index(op.f('ix_tbl_news_arti_src_nm'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_pub_ts'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_crt_ts'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_arti_url'), table_name='tbl_news_arti')
    op.drop_index('idx_news_arti_pub_src', table_name='tbl_news_arti')
    op.drop_table('tbl_news_arti')
    op.drop_index(op.f('ix_tbl_gpu_prc_hist_ts'), table_name='tbl_gpu_prc_hist')
    op.drop_index(op.f('ix_tbl_gpu_prc_hist_prv_id'), table_name='tbl_gpu_prc_hist')
    op.drop_index(op.f('ix_tbl_gpu_prc_hist_gpu_mdl'), table_name='tbl_gpu_prc_hist')
    op.drop_index(op.f('ix_tbl_gpu_prc_hist_cpu_mdl'), table_name='tbl_gpu_prc_hist')
    op.drop_index('idx_gpu_prc_prv_ts', table_name='tbl_gpu_prc_hist')
    op.drop_index('idx_gpu_prc_mdl_ts', table_name='tbl_gpu_prc_hist')
    op.drop_table('tbl_gpu_prc_hist')
    op.drop_index(op.f('ix_tbl_fin_mkt_hist_ts'), table_name='tbl_fin_mkt_hist')
    op.drop_index(op.f('ix_tbl_fin_mkt_hist_sym_cd'), table_name='tbl_fin_mkt_hist')
    op.drop_index(op.f('ix_tbl_fin_mkt_hist_ast_typ'), table_name='tbl_fin_mkt_hist')
    op.drop_index('idx_fin_mkt_sym_ts', table_name='tbl_fin_mkt_hist')
    op.drop_table('tbl_fin_mkt_hist')
    op.drop_index(op.f('ix_storage_providers_name'), table_name='storage_providers')
    op.drop_table('storage_providers')
    op.drop_index(op.f('ix_schedule_configs_provider_id'), table_name='schedule_configs')
    op.drop_table('schedule_configs')
    op.drop_index(op.f('ix_providers_slug'), table_name='providers')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_memory_manufacturers_name'), table_name='memory_manufacturers')
    op.drop_table('memory_manufacturers')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_table('gpu_manufacturers')
    op.drop_index(op.f('ix_data_quality_issues_run_id'), table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_observation_id'), table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    op.drop_table('data_licenses')
    op.drop_table('cpu_manufacturers')
    op.drop_index('ix_collection_runs_provider_started', table_name='collection_runs')
    op.drop_index(op.f('ix_collection_runs_provider_id'), table_name='collection_runs')
    op.drop_table('collection_runs')
    op.drop_table('SYS_CD_GROUP_BAS')
    op.drop_table('SYS_CD_BAS')
    # ### end Alembic commands ###
