"""add_paper_tables

Revision ID: a651c44567cd
Revises: 576a294b22a9
Create Date: 2026-07-24 01:59:16.024360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a651c44567cd'
down_revision: Union[str, Sequence[str], None] = '576a294b22a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_paper_source',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_paper_source_name'), 'tbl_paper_source', ['name'], unique=True)
    op.create_table('tbl_paper_tag',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_paper_tag_name'), 'tbl_paper_tag', ['name'], unique=True)
    op.create_table('tbl_paper_article',
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_ko', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('is_analyzed', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['tbl_paper_source.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_paper_article_pub_src', 'tbl_paper_article', ['published_at', 'source'], unique=False)
    op.create_index(op.f('ix_tbl_paper_article_category'), 'tbl_paper_article', ['category'], unique=False)
    op.create_index(op.f('ix_tbl_paper_article_external_id'), 'tbl_paper_article', ['external_id'], unique=True)
    op.create_index(op.f('ix_tbl_paper_article_published_at'), 'tbl_paper_article', ['published_at'], unique=False)
    op.create_index(op.f('ix_tbl_paper_article_source'), 'tbl_paper_article', ['source'], unique=False)
    op.create_index(op.f('ix_tbl_paper_article_source_id'), 'tbl_paper_article', ['source_id'], unique=False)
    op.create_table('tbl_paper_article_tag',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['tbl_paper_article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tbl_paper_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_paper_article_tag_unique', 'tbl_paper_article_tag', ['article_id', 'tag_id'], unique=True)
    op.create_index(op.f('ix_tbl_paper_article_tag_article_id'), 'tbl_paper_article_tag', ['article_id'], unique=False)
    op.create_index(op.f('ix_tbl_paper_article_tag_tag_id'), 'tbl_paper_article_tag', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_paper_article_tag_tag_id'), table_name='tbl_paper_article_tag')
    op.drop_index(op.f('ix_tbl_paper_article_tag_article_id'), table_name='tbl_paper_article_tag')
    op.drop_index('idx_paper_article_tag_unique', table_name='tbl_paper_article_tag')
    op.drop_table('tbl_paper_article_tag')
    op.drop_index(op.f('ix_tbl_paper_article_source_id'), table_name='tbl_paper_article')
    op.drop_index(op.f('ix_tbl_paper_article_source'), table_name='tbl_paper_article')
    op.drop_index(op.f('ix_tbl_paper_article_published_at'), table_name='tbl_paper_article')
    op.drop_index(op.f('ix_tbl_paper_article_external_id'), table_name='tbl_paper_article')
    op.drop_index(op.f('ix_tbl_paper_article_category'), table_name='tbl_paper_article')
    op.drop_index('idx_paper_article_pub_src', table_name='tbl_paper_article')
    op.drop_table('tbl_paper_article')
    op.drop_index(op.f('ix_tbl_paper_tag_name'), table_name='tbl_paper_tag')
    op.drop_table('tbl_paper_tag')
    op.drop_index(op.f('ix_tbl_paper_source_name'), table_name='tbl_paper_source')
    op.drop_table('tbl_paper_source')
    # ### end Alembic commands ###
