"""add baremetal flag

Revision ID: b705f9282bbb
Revises: 0c71f41d0ff2
Create Date: 2026-07-23 16:06:12.664094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b705f9282bbb'
down_revision: Union[str, Sequence[str], None] = '0c71f41d0ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance_offerings', sa.Column('is_baremetal', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance_offerings', 'is_baremetal')
    # ### end Alembic commands ###
