"""Add ForeignKey to SYS_CD_BAS

Revision ID: ba50dd389d86
Revises: a00ecbf6abd3
Create Date: 2026-07-23 12:04:57.561718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba50dd389d86'
down_revision: Union[str, Sequence[str], None] = 'a00ecbf6abd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'SYS_CD_BAS', 'SYS_CD_GROUP_BAS', ['SYS_GROUP_ID'], ['SYS_GROUP_ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SYS_CD_BAS', type_='foreignkey')
    # ### end Alembic commands ###
