"""Add SysBatSchHist

Revision ID: cc1d03ac1994
Revises: a651c44567cd
Create Date: 2026-07-24 11:25:28.571227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc1d03ac1994'
down_revision: Union[str, Sequence[str], None] = 'a651c44567cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SYS_BAT_SCH_HIST',
    sa.Column('SEQ', sa.Integer(), autoincrement=True, nullable=False, comment='이력 일련번호'),
    sa.Column('BAT_ID', sa.String(length=50), nullable=False, comment='배치 마스터 ID'),
    sa.Column('JOB_ID', sa.String(length=50), nullable=False, comment='세부 잡 ID'),
    sa.Column('STATUS', sa.String(length=20), nullable=False, comment='실행 결과 (SUCCESS / FAIL)'),
    sa.Column('START_DT', sa.DateTime(), nullable=False, comment='시작 일시'),
    sa.Column('END_DT', sa.DateTime(), nullable=False, comment='종료 일시'),
    sa.Column('ERR_MSG', sa.Text(), nullable=True, comment='에러 발생 시 전문(Traceback)'),
    sa.Column('CRT_DT', sa.DateTime(), nullable=True, comment='생성일시'),
    sa.PrimaryKeyConstraint('SEQ')
    )
    op.create_index(op.f('ix_SYS_BAT_SCH_HIST_BAT_ID'), 'SYS_BAT_SCH_HIST', ['BAT_ID'], unique=False)
    op.create_index(op.f('ix_SYS_BAT_SCH_HIST_JOB_ID'), 'SYS_BAT_SCH_HIST', ['JOB_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SYS_BAT_SCH_HIST_JOB_ID'), table_name='SYS_BAT_SCH_HIST')
    op.drop_index(op.f('ix_SYS_BAT_SCH_HIST_BAT_ID'), table_name='SYS_BAT_SCH_HIST')
    op.drop_table('SYS_BAT_SCH_HIST')
    # ### end Alembic commands ###
