"""Add memory and storage

Revision ID: d11a3383e975
Revises: 300276d985a7
Create Date: 2026-07-22 09:02:41.260064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11a3383e975'
down_revision: Union[str, Sequence[str], None] = '300276d985a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_manufacturers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_manufacturers_name'), 'memory_manufacturers', ['name'], unique=True)
    op.create_table('storage_providers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_providers_name'), 'storage_providers', ['name'], unique=True)
    op.create_table('memory_modules',
    sa.Column('manufacturer_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('capacity_gb', sa.Float(), nullable=False),
    sa.Column('speed_mhz', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['memory_manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_modules_manufacturer_id'), 'memory_modules', ['manufacturer_id'], unique=False)
    op.create_table('storage_tiers',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price_per_gb_month', sa.Float(), nullable=False),
    sa.Column('egress_price_per_gb', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['storage_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_tiers_provider_id'), 'storage_tiers', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_tiers_provider_id'), table_name='storage_tiers')
    op.drop_table('storage_tiers')
    op.drop_index(op.f('ix_memory_modules_manufacturer_id'), table_name='memory_modules')
    op.drop_table('memory_modules')
    op.drop_index(op.f('ix_storage_providers_name'), table_name='storage_providers')
    op.drop_table('storage_providers')
    op.drop_index(op.f('ix_memory_manufacturers_name'), table_name='memory_manufacturers')
    op.drop_table('memory_manufacturers')
    # ### end Alembic commands ###
