"""refactor(news): migrate to tbl_news_article and add tags

Revision ID: dcd94953ed78
Revises: 7402e5853cfc
Create Date: 2026-07-23 22:56:51.069276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcd94953ed78'
down_revision: Union[str, Sequence[str], None] = '7402e5853cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_news_source',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_news_source_name'), 'tbl_news_source', ['name'], unique=True)
    op.create_table('tbl_news_tag',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_news_tag_name'), 'tbl_news_tag', ['name'], unique=True)
    op.create_table('tbl_news_article',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('canonical_url', sa.String(length=1000), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_domain', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('is_semiconductor_related', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('matched_keywords', sa.String(length=500), nullable=True),
    sa.Column('collection_tier', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['tbl_news_source.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_article_pub_src', 'tbl_news_article', ['published_at', 'source_name'], unique=False)
    op.create_index(op.f('ix_tbl_news_article_category'), 'tbl_news_article', ['category'], unique=False)
    op.create_index(op.f('ix_tbl_news_article_content_type'), 'tbl_news_article', ['content_type'], unique=False)
    op.create_index(op.f('ix_tbl_news_article_created_at'), 'tbl_news_article', ['created_at'], unique=False)
    op.create_index(op.f('ix_tbl_news_article_published_at'), 'tbl_news_article', ['published_at'], unique=False)
    op.create_index(op.f('ix_tbl_news_article_source_id'), 'tbl_news_article', ['source_id'], unique=False)
    op.create_index(op.f('ix_tbl_news_article_source_name'), 'tbl_news_article', ['source_name'], unique=False)
    op.create_index(op.f('ix_tbl_news_article_url'), 'tbl_news_article', ['url'], unique=True)
    op.create_table('tbl_news_article_tag',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['tbl_news_article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tbl_news_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_article_tag_unique', 'tbl_news_article_tag', ['article_id', 'tag_id'], unique=True)
    op.create_index(op.f('ix_tbl_news_article_tag_article_id'), 'tbl_news_article_tag', ['article_id'], unique=False)
    op.create_index(op.f('ix_tbl_news_article_tag_tag_id'), 'tbl_news_article_tag', ['tag_id'], unique=False)
    op.drop_index(op.f('idx_news_arti_pub_src'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_category'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_content_type'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_created_at'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_published_at'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_source_name'), table_name='tbl_news_arti')
    op.drop_index(op.f('ix_tbl_news_arti_url'), table_name='tbl_news_arti')
    op.drop_table('tbl_news_arti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_news_arti',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('canonical_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('source_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('source_domain', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('collected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_semiconductor_related', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('matched_keywords', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('collection_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_news_arti_pkey'))
    )
    op.create_index(op.f('ix_tbl_news_arti_url'), 'tbl_news_arti', ['url'], unique=True)
    op.create_index(op.f('ix_tbl_news_arti_source_name'), 'tbl_news_arti', ['source_name'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_published_at'), 'tbl_news_arti', ['published_at'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_created_at'), 'tbl_news_arti', ['created_at'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_content_type'), 'tbl_news_arti', ['content_type'], unique=False)
    op.create_index(op.f('ix_tbl_news_arti_category'), 'tbl_news_arti', ['category'], unique=False)
    op.create_index(op.f('idx_news_arti_pub_src'), 'tbl_news_arti', ['published_at', 'source_name'], unique=False)
    op.drop_index(op.f('ix_tbl_news_article_tag_tag_id'), table_name='tbl_news_article_tag')
    op.drop_index(op.f('ix_tbl_news_article_tag_article_id'), table_name='tbl_news_article_tag')
    op.drop_index('idx_article_tag_unique', table_name='tbl_news_article_tag')
    op.drop_table('tbl_news_article_tag')
    op.drop_index(op.f('ix_tbl_news_article_url'), table_name='tbl_news_article')
    op.drop_index(op.f('ix_tbl_news_article_source_name'), table_name='tbl_news_article')
    op.drop_index(op.f('ix_tbl_news_article_source_id'), table_name='tbl_news_article')
    op.drop_index(op.f('ix_tbl_news_article_published_at'), table_name='tbl_news_article')
    op.drop_index(op.f('ix_tbl_news_article_created_at'), table_name='tbl_news_article')
    op.drop_index(op.f('ix_tbl_news_article_content_type'), table_name='tbl_news_article')
    op.drop_index(op.f('ix_tbl_news_article_category'), table_name='tbl_news_article')
    op.drop_index('idx_news_article_pub_src', table_name='tbl_news_article')
    op.drop_table('tbl_news_article')
    op.drop_index(op.f('ix_tbl_news_tag_name'), table_name='tbl_news_tag')
    op.drop_table('tbl_news_tag')
    op.drop_index(op.f('ix_tbl_news_source_name'), table_name='tbl_news_source')
    op.drop_table('tbl_news_source')
    # ### end Alembic commands ###
