"""add tbl_news_daily_briefing

Revision ID: e4116f3c451b
Revises: dcd94953ed78
Create Date: 2026-07-23 23:12:38.445215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4116f3c451b'
down_revision: Union[str, Sequence[str], None] = 'dcd94953ed78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_news_daily_briefing',
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('source_article_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_briefing_date_cat', 'tbl_news_daily_briefing', ['date', 'category'], unique=True)
    op.create_index(op.f('ix_tbl_news_daily_briefing_category'), 'tbl_news_daily_briefing', ['category'], unique=False)
    op.create_index(op.f('ix_tbl_news_daily_briefing_date'), 'tbl_news_daily_briefing', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_news_daily_briefing_date'), table_name='tbl_news_daily_briefing')
    op.drop_index(op.f('ix_tbl_news_daily_briefing_category'), table_name='tbl_news_daily_briefing')
    op.drop_index('idx_briefing_date_cat', table_name='tbl_news_daily_briefing')
    op.drop_table('tbl_news_daily_briefing')
    # ### end Alembic commands ###
