"""add ai pricing

Revision ID: f6c292de18f4
Revises: cc1d03ac1994
Create Date: 2026-07-24 14:27:47.982578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c292de18f4'
down_revision: Union[str, Sequence[str], None] = 'cc1d03ac1994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_ai_model_master',
    sa.Column('model_code', sa.String(length=100), nullable=False, comment='OpenRouter 모델 코드 (예: openai/gpt-4o)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='표시할 모델명'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='제조사 (OpenAI, Anthropic 등)'),
    sa.Column('tier', sa.String(length=20), nullable=False, comment='성능 체급 (Tier 0 ~ Tier 3)'),
    sa.Column('context_length', sa.Integer(), nullable=True, comment='지원하는 컨텍스트 윈도우 크기'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_ai_model_master_model_code'), 'tbl_ai_model_master', ['model_code'], unique=True)
    op.create_index(op.f('ix_tbl_ai_model_master_provider'), 'tbl_ai_model_master', ['provider'], unique=False)
    op.create_index(op.f('ix_tbl_ai_model_master_tier'), 'tbl_ai_model_master', ['tier'], unique=False)
    op.create_table('tbl_ai_model_price_history',
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('collected_date', sa.Date(), nullable=False, comment='수집 일자 (선차트 x축)'),
    sa.Column('input_price_1m', sa.Float(), nullable=False, comment='100만 토큰 당 Input 가격 (USD)'),
    sa.Column('output_price_1m', sa.Float(), nullable=False, comment='100만 토큰 당 Output 가격 (USD)'),
    sa.Column('cached_input_price_1m', sa.Float(), nullable=True, comment='100만 토큰 당 Cached Input 가격 (USD)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['tbl_ai_model_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_model_price_hist_unique', 'tbl_ai_model_price_history', ['model_id', 'collected_date'], unique=True)
    op.create_index(op.f('ix_tbl_ai_model_price_history_collected_date'), 'tbl_ai_model_price_history', ['collected_date'], unique=False)
    op.create_index(op.f('ix_tbl_ai_model_price_history_model_id'), 'tbl_ai_model_price_history', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_ai_model_price_history_model_id'), table_name='tbl_ai_model_price_history')
    op.drop_index(op.f('ix_tbl_ai_model_price_history_collected_date'), table_name='tbl_ai_model_price_history')
    op.drop_index('idx_ai_model_price_hist_unique', table_name='tbl_ai_model_price_history')
    op.drop_table('tbl_ai_model_price_history')
    op.drop_index(op.f('ix_tbl_ai_model_master_tier'), table_name='tbl_ai_model_master')
    op.drop_index(op.f('ix_tbl_ai_model_master_provider'), table_name='tbl_ai_model_master')
    op.drop_index(op.f('ix_tbl_ai_model_master_model_code'), table_name='tbl_ai_model_master')
    op.drop_table('tbl_ai_model_master')
    # ### end Alembic commands ###
