"""add error log

Revision ID: feb9aee8f12a
Revises: f6c292de18f4
Create Date: 2026-07-24 14:46:06.283117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb9aee8f12a'
down_revision: Union[str, Sequence[str], None] = 'f6c292de18f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_error_log',
    sa.Column('severity', sa.String(length=20), nullable=False, comment='CRITICAL, NORMAL, LOW'),
    sa.Column('source', sa.String(length=100), nullable=False, comment='어디서 에러가 났는지 (e.g. ai_pricing_crawler)'),
    sa.Column('error_type', sa.String(length=100), nullable=False, comment='Exception 클래스 이름'),
    sa.Column('error_message', sa.Text(), nullable=False, comment='에러 메시지'),
    sa.Column('traceback', sa.Text(), nullable=True, comment='스택 트레이스'),
    sa.Column('context_data', sa.Text(), nullable=True, comment='발생 당시의 변수나 추가 정보(JSON)'),
    sa.Column('is_sent', sa.Boolean(), nullable=False, comment='텔레그램 발송 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_error_log_is_sent'), 'tbl_error_log', ['is_sent'], unique=False)
    op.create_index(op.f('ix_tbl_error_log_severity'), 'tbl_error_log', ['severity'], unique=False)
    op.create_index(op.f('ix_tbl_error_log_source'), 'tbl_error_log', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_error_log_source'), table_name='tbl_error_log')
    op.drop_index(op.f('ix_tbl_error_log_severity'), table_name='tbl_error_log')
    op.drop_index(op.f('ix_tbl_error_log_is_sent'), table_name='tbl_error_log')
    op.drop_table('tbl_error_log')
    # ### end Alembic commands ###
